// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "borrowedBook": "الكتب مستعارة",
  "sales": "المبيعات",
  "selectYear": "تحديد السنة",
  "purchasedBooks": "الكتب المشتراة",
  "search": "بحث",
  "returned": "تم إرجاعه",
  "category": "التصنيفات",
  "tap": "اضغط",
  "cancle": "إلغاء",
  "ok": "تم",
  "endmonth": "شهر النهاية",
  "startmonth": "شهر البداية",
  "year": "السنة",
  "scienceFiction": "خيال علمي",
  "cookbooks": "كتب طهي",
  "poetry": "شعر",
  "romance": "رومانسي",
  "mystery": "ألغاز",
  "humor": "Humor",
  "comicBooks": "كتب هزلية",
  "graphicNovel": "روايات مصورة",
  "adventure": "مغامرات",
  "historicalFiction": "Historical Fiction",
  "fantasy": "فانتازيا",
  "crime": "جريمة",
  "horror": "رعب",
  "childrensBooks": "كتب أطفال",
  "biography": "سيرة ذاتية",
  "health&Fitness": "صحة و رشاقة",
  "religion": "كتب دينية",
  "education": "كتب تعليمية",
  "password": "كلمة السر",
  "enteryourpassword": "أدخل كلمة السر",
  "newpassword": "كلمة السر الجديدة",
  "confirm": "تأكيد كلمة السر",
  "CantbeEmpty": "لا يمكن ترك الحقل فارغ",
  "mustbethesame": "يجب أن تكون مماثلة لكلمة السر الجديدة",
  "loanBooks": "الكتب المعارة",
  "soldBooks": "الكتب المباعة",
  "selectBook": "اختيار الكتب",
  "addOffer": "إضافة عرض",
  "updateOffer": "تعديل عرض",
  "price": "السعر",
  "tryagain": "حاول مجدداً",
  "enternumber": "أدخل رقم",
  "chooseanaccount": "اختر حساب",
  "tocontinuetoadmin": "للمتابعة كآدمن ",
  "addanotheraccount": "إضافة حساب آخر",
  "googleshare": "سنقوم بمشاركة اسمك وصورة حسابك الشخصي مع التطبيق",
  "firstname": "الاسم الأول",
  "middlename": "الاسم الأوسط",
  "lastname": "الكنية",
  "yourphonenumber": "رقم هاتفك",
  "libname": "اسم المكتبة",
  "openandclose": "تحديد وقت الفتح والإغلاق",
  "select": "تحديد",
  "continue": "متابعة",
  "signup": "إنشاء حساب",
  "youremail": "البريد الإلكتروني",
  "register": "تسجيل",
  "alreadyhave": "لديك حساب مسبقاً",
  "login": "تسجيل دخول",
  "signupwithgoogle": "إنشاء حساب باستخدام google",
  "signupwithfacebook": "إنشار حساب باستخدام facebook",
  "libaddress": "قم بإضافة عنوان مكتبتك",
  "title": "العنوان",
  "area": "المنطقة",
  "street": "الشارع",
  "floor": "الطابق",
  "near": "بالقرب من",
  "details": "تفاصيل",
  "getstarted": "هيا نبدأ",
  "pleaseaddphoto": "قم بإضافة صورة لمكتبتك",
  "addphoto": "إضافة صورة",
  "skip": "تخطي",
  "saved": "المحفوظات",
  "bought": "المشتريات",
  "borrowed": "المستعارة",
  "Myonline": "My Online",
  "setting": "إعدادات",
  "Myaddress": "عنواني",
  "addbook": "إضافة كتاب",
  "name": "الاسم",
  "summary": "ملخص",
  "Pagesnumber": "عدد الصفحات",
  "purchasingprice": "سعر الشراء",
  "sellingprice": "سعر المبيع",
  "quantity": "الكمية",
  "authors": "الكاتب",
  "recent": "الأخيرة",
  "clearAll": "حذف الكل",
  "topSearchedBooks": "الكتب الأكثر بحثاً",
  "gallery": "المعرض",
  "camera": "كاميرا",
  "description": "الوصف",
  "bookforborrow:": "معلومات الاستعارة",
  "quotes": "الاقتباسات",
  "addQuote": "إضافة اقتباس",
  "failuer": "فشل",
  "pleaseswaptotryagain": "قم بالسحب للمحاولة مجدداً",
  "save": "حفظ",
  "favourt": "المفضلة",
  "person": "شخصي",
  "orderBook": "طلب كتاب",
  "addtoshoppingcart": "إضافة إلى السلة   ",
  "totalPrice": "السعر الإجمالي",
  "selectatleast3kindsyoulike :": "اختر على الأقل 3 أنواع تفضلها",
  "comments": "التعليقات",
  "addcomment": "   إضافة تعليق",
  "library": "المكتبة",
  "numofpages": "عدد الصفحات : ",
  "comment": "تعليق",
  "allQuotes": "كل الاقتباسات",
  "state": "الحالة",
  "categories": "التصنيفات :",
  "buyBook": "شراء كتاب",
  "explore": "اكتشاف",
  "offers": "العروض",
  "books": "الكتب",
  "email": "البريد الإلكتروني",
  "openTime": "وقت الفتح",
  "closeTime": "وقن الإغلاق",
  "address": "العنوان",
  "contact": "التواصل",
  "pleaseenteraddress": "ادخل العنوان",
  "pleaseenterminimum10characters": "أدخل على الأقل 10 حروف",
  "logIn": "تسجيل دخول",
  "forgetyourpassword": "نسيت كلمة السر",
  "donthaveanaccount": "ليس لديك حساب؟",
  "confirmpasswordandpasswordaredeferent": "كلمة السر والتأكيد غير متماثلة",
  "send": "إرسال",
  "addanorder": "إضافة طلب",
  "nodateSelected": "لم يتم تحديد تاريخ",
  "yourInformation": "معلوماتك",
  "male": "ذكر",
  "female": "أنثى",
  "classics": "كلاسيكي",
  "action": "أكشن",
  "trueCrime": "جريمة واقعية"
};
static const Map<String,dynamic> en = {
  "borrowedBook": "Borrowed Books",
  "sales": "Sales",
  "selectYear": "select year",
  "purchasedBooks": "Purchased Books",
  "search": "Search",
  "returned": "returned",
  "category": "Category",
  "tap": "tap",
  "cancle": "Cancle",
  "ok": "Done",
  "endmonth": "End month",
  "startmonth": "start month",
  "year": "Year",
  "scienceFiction": "Science Fiction",
  "cookbooks": "Cooking books",
  "poetry": "Poetry",
  "romance": "Romance",
  "mystery": "Mystery",
  "humor": "Humor",
  "comicBooks": "Comic Books",
  "graphicNovel": "Graphic Novel",
  "adventure": "Adventure",
  "historicalFiction": "Historical Fiction",
  "fantasy": "Fantasy",
  "crime": "Crime",
  "horror": "Horror",
  "childrensBooks": "Children's Books",
  "biography": "Biography",
  "health&Fitness": "Health & Fitness",
  "religion": "Religion",
  "education": "Education",
  "password": "Password",
  "enteryourpassword": "Enter your password",
  "newpassword": "New password",
  "confirm": "Confirm",
  "CantbeEmpty": "Can't be Empty",
  "mustbethesame": "must be the same",
  "loanBooks": "Loan Books",
  "soldBooks": "Sold Books",
  "selectBook": "Select Book",
  "addOffer": "Add Offer",
  "updateOffer": "Update Offer",
  "price": "Price",
  "tryagain": "Try again",
  "enternumber": "Enter number",
  "chooseanaccount": "Choose an account",
  "tocontinuetoadmin": "Check your email and verify account to continue your regiter",
  "addanotheraccount": "Add another account",
  "googleshare": "",
  "firstname": "First name",
  "middlename": "Middle name",
  "lastname": "Last name",
  "yourphonenumber": "Your phone number",
  "libname": "Library name",
  "openandclose": "Select open and close time",
  "select": "Select",
  "continue": "Continue",
  "yourinfo": "Your information",
  "signup": "SignUp",
  "youremail": "Your email",
  "register": "Register",
  "alreadyhave": "already have an account",
  "login": "Log in",
  "signupwithgoogle": "Sign up with google",
  "signupwithfacebook": "Sign up with facebook",
  "libaddress": "Please add your library address",
  "title": "Title",
  "area": "Area",
  "street": "Street",
  "floor": "Floor",
  "near": "Near",
  "details": "Details",
  "getstarted": "Let's get started",
  "pleaseaddphoto": "Please add photo to your library",
  "addphoto": "Add photo",
  "skip": "Skip",
  "saved": "Saved",
  "bought": "Bought",
  "borrowed": "Borrowed",
  "Myonline": "My Online",
  "setting": "Setting",
  "Myaddress": "my address",
  "addbook": "addbook",
  "name": "Name",
  "summary": "Summary",
  "Pagesnumber": "Page's number",
  "purchasingprice": "Purchasing price",
  "sellingprice": "Selling price",
  "quantity": "Quantity",
  "authors": "Authors",
  "recent": "Recent",
  "clearAll": "clearAll",
  "topSearchedBooks": "Top Searched Books",
  "gallery": "gallery",
  "camera": "camera",
  "description": "Description",
  "bookforborrow:": "bookS for borrow:",
  "quotes": "Quotes",
  "addQuote": "Add Quote",
  "failer": "Failuer",
  "pleaseswaptotryagain": "please swap to try again",
  "save": "save",
  "favourt": "favourt",
  "person": "person",
  "orderBook": "Order Book",
  "addtoshoppingcart": "Add to shopping cart   ",
  "totalPrice": "Total Price : ",
  "selectatleast3kindsyoulike :": "Select at least 3 kinds you like :",
  "comments": "Comments",
  "addcomment": "   addcomment",
  "library": "library",
  "numofpages": "num of pages : ",
  "comment": "Comment",
  "allQuotes": "allQuotes",
  "state": "State",
  "categories": "Categories :",
  "buyBook": "buyBook",
  "explore": "Explore",
  "offers": "Offers",
  "books": "Books",
  "contact": "Contact",
  "email": "email",
  "openTime": "Open Time",
  "closeTime": "Close Time",
  "address": "Address",
  "pleaseenteraddress": "Please enter address",
  "pleaseenterminimum10characters": "Please enter minimum 10 characters",
  "logIn": "Log In",
  "forgetyourpassword": "Forget your password",
  "donthaveanaccount": "Dont have an account?",
  "confirmpasswordandpasswordaredeferent": "confirm password and password are deferent",
  "myShoppingCard": "My Shopping Card",
  "send": "send",
  "addanorder": "add an order",
  "nodateSelected": "No date Selected!",
  "yourInformation": "Your Information",
  "male": "male",
  "female": "female",
  "classics": "Classics",
  "action": "Action",
  "trueCrime": "True Crime"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
